# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=mariadb

before_install:
  - docker pull alpine
  - docker pull demyx/nginx
  - docker pull demyx/wordpress
  - docker pull demyx/wordpress:cli
  - docker pull demyx/utilities
  - docker network create demyx

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - docker run -d --name="$DEMYX_REPOSITORY" --network=demyx -e DEMYX_DATABASE=demyx -e DEMYX_USERNAME=demyx -e DEMYX_PASSWORD=demyx -e DEMYX_ROOT_PASSWORD=demyx demyx/"$DEMYX_REPOSITORY"
  - docker run -d --name=demyx_wp --network=demyx -v demyx_wp:/demyx -e DEMYX_DB_HOST="$DEMYX_REPOSITORY" -e DEMYX_DB_NAME=demyx -e DEMYX_DB_USER=demyx -e DEMYX_DB_PASSWORD=demyx demyx/wordpress
  - sleep 5
  - docker run --network=demyx --volumes-from=demyx_wp --workdir=/demyx demyx/wordpress:cli core install --url=http://localhost --title=demyx --admin_user=demyx --admin_password=demyx --admin_email=info@domain.tld --skip-email
  - docker run -dit --name=demyx_nx --network=demyx -v demyx_wp:/demyx -e DEMYX_WORDPRESS=true -e DEMYX_WORDPRESS_CONTAINER=demyx_wp -e DEMYX_WORDPRESS_CONTAINER_PORT=9000 -e DEMYX_DOMAIN=localhost demyx/nginx
  - sleep 5
  - docker exec demyx_nx sh -c "wget -qO- http://localhost | grep 'Hello world'"

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - bash travis.sh
